#ARDUINO_DIR   = /usr/share/arduino
ARDUINO_DIR   = /opt/arduino-1.0.5
ARDMK_DIR     = /opt/Arduino-Makefile
AVR_TOOLS_DIR = /usr
USER_LIB_PATH = ../../..

BOARD_TAG    = mega2560
ARDUINO_PORT = /dev/ttyACM*
ARDUINO_LIBS = SoftwareSerial ANT SPI LCD_5110


include ${ARDMK_DIR}/Arduino.mk


