ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = /usr
AVR_TOOLS_DIR = /usr
USER_LIB_PATH = /home/picuntu/github/ANT-arduino/libraries

BOARD_TAG    = mega2560
ARDUINO_PORT = /dev/ttyACM*
ARDUINO_LIBS = SoftwareSerial ANT


include /usr/share/arduino/Arduino.mk


